#ifndef HEADER_E4D23F681A362C5B
#define HEADER_E4D23F681A362C5B

/* Warning: This file is automatically generated by AX-RadioLAB.
Manual changes are overwritten! */

#include "../COMMON/axradio.h"


//#define DEBUGMSG

// allow sleep (not just standby)
#define MCU_SLEEP
#define WTIMER0_CLKSRC	CLKSRC_LPOSC
#define WTIMER0_PRESCALER 0x01

extern const struct axradio_address __code remoteaddr;
extern const struct axradio_address_mask __code localaddr;

extern const uint16_t __code lpxosc_settlingtime;

#endif // header guard
